### PR TITLE
Fix spelling errors in multiple files

### PR DESCRIPTION
**Pull request by jgstew**
Fix spelling errors in multiple files

### CODE REVIEW

**Comment by jgstew** [comment]
I just signed the CLA but I couldn't add the email address that I used for these commits.

**Comment by jgstew** [comment]
I added a github action codespell to automatic check for spelling errors, and it should automatically annotate found spelling errors on PRs.

**Comment by sethvargo** [comment]
> I added a github action codespell to automatic check for spelling errors, and it should automatically annotate found spelling errors on PRs.

Hi @jgstew - thank you for the PR. I'm happy to merge the spelling fixes, but I don't want to add a GitHub Action for this.

**Comment by jgstew** [comment]
@sethvargo  makes sense, thanks!

**Pull request closed without merging**
