### PR TITLE
Support reading token from file

### PR DESCRIPTION
**Pull request by juho9000**
This PR adds option to read a token from a file instead of going through Github API to grab the token to be used with Workload Identity Federation. AWS already supports this in their similar action so I thought this would be a good addition here aswell.

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @juho9000 - thank you for the pull request. What is the use case for doing this?

**Comment by juho9000** [comment]
> Hi @juho9000 - thank you for the pull request. What is the use case for doing this?

Hi. Atleast I know of a scenario where Github Enterprise Server is used instead of Github.com. Companies using GHES may keep it locked away from public internet entirely, including the OIDC discovery endpoint. In this case one can have a separate service that is reachable from GHES as well as public internet. The service accepts the Github token, verifies it, signs it again with the same claims while changing the issuer. The token can then be used with GCP Web Identity Federation in the same way as a regular Github OIDC token.

**Comment by sethvargo** [comment]
> > Hi @juho9000 - thank you for the pull request. What is the use case for doing this?
> 
> Hi. Atleast I know of a scenario where Github Enterprise Server is used instead of Github.com. Companies using GHES may keep it locked away from public internet entirely, including the OIDC discovery endpoint. In this case one can have a separate service that is reachable from GHES as well as public internet. The service accepts the Github token, verifies it, signs it again with the same claims while changing the issuer. The token can then be used with GCP Workload Identity Federation in the same way as a regular Github OIDC token.

If customers are using self-hosted runners, then should use the native machine identity to authenticate ([Application Default Credentials](https://cloud.google.com/docs/authentication/provide-credentials-adc)). The point of OIDC is that you trust the underlying infrastructure, so the underlying infrastructure should be providing the claims.

**Comment by sethvargo** [comment]
GHES implies self-hosted runners: https://docs.github.com/en/enterprise-server@3.14/admin/managing-github-actions-for-your-enterprise/getting-started-with-github-actions-for-your-enterprise/getting-started-with-github-actions-for-github-enterprise-server#adding-self-hosted-runners

screenshot-20241001212344@2x

**Comment by juho9000** [comment]
Sure, but I do not understand how these things are connected. If you run self hosted GHES and self hosted runners (outside of GCP) while GHES itself is not available publicly your only way to authenticate to GCP would be static credentials, which does not sound good. All this aside, the ability to read the token from a file is something AWS already supports in their similar action. Why not have the possibility here too?

**Comment by zetaab** [comment]
AWS support https://github.com/aws-actions/configure-aws-credentials/blob/main/action.yml#L27-L29

**Comment by sethvargo** [comment]
> Sure, but I do not understand how these things are connected. If you run self hosted GHES and self hosted runners (outside of GCP) while GHES itself is not available publicly your only way to authenticate to GCP would be static credentials, which does not sound good.

If the self-hosted runners are on different infrastructure (e.g. AWS, Azure) then you configure the OIDC exchange at that level (e.g. [exchange an EC2 instance profile for a GCP credential](https://aws.amazon.com/blogs/security/access-aws-using-a-google-cloud-platform-native-workload-identity/)) (the [opposite is also possible](https://aws.amazon.com/blogs/security/access-aws-using-a-google-cloud-platform-native-workload-identity/)).

Additionally, using this token file is _also_ a static credential.

> All this aside, the ability to read the token from a file is something AWS already supports in their similar action. Why not have the possibility here too?

Because it's an [incorrect solution to the wrong problem](https://xyproblem.info). The point of OIDC is to exchange the machine/workload identity for another credential. Self-hosted GitHub Actions runners already have an identity provided by their underlying runtime.

Putting aside the fact that GitHub [requires exposing the `.well-known` endpoints as a mandatory prerequisite for OIDC](https://docs.github.com/en/enterprise-server@3.14/admin/managing-github-actions-for-your-enterprise/enabling-github-actions-for-github-enterprise-server/enabling-github-actions-with-google-cloud-storage#prerequisites)... if you _must_ trust the signatures from GHES, then the proper approach is to [sync the JWKS from on-prem into GCP with a small microservice or cron-job](https://cloud.google.com/iam/docs/workload-identity-federation-with-other-providers#manage-oidc-keys). It would periodically run something like:

```sh
curl -sfLO "https://github.company.internal/.well-known/jwks" && \
  gcloud iam workload-identity-pools providers update-oidc "my-provider" --jwk-json-path="./jwks"
```

> ...there is no way to authenticate from Github enterprise towards google cloud in any other way than static credentials. This PR could bring mechanism to use "OIDC proxy" to get access working towards google cloud by using Github enterprise.

As I said above, that is simply untrue. Again, this approach is solving the _wrong problem_, and it's concerning that AWS would even allow this functionality in their action. You don't need an OIDC proxy, you need to sync the JWKS from GHES to GCP. The script I provided above is an example of how to do that. Or you could run a reverse proxy that _is_ exposed to the public Internet and only exposes the openid-connect and jwks endpoints.

**Comment by juho9000** [comment]
> If the self-hosted runners are on different infrastructure (e.g. AWS, Azure) then you configure the OIDC exchange at that level (e.g. [exchange an EC2 instance profile for a GCP credential](https://aws.amazon.com/blogs/security/access-aws-using-a-google-cloud-platform-native-workload-identity/)) (the [opposite is also possible](https://aws.amazon.com/blogs/security/access-aws-using-a-google-cloud-platform-native-workload-identity/)).

The runners are hosted on-premises without a possibility to have such exchange.

> Additionally, using this token file is _also_ a static credential.

I disagree with your argument here. It is the same exact token that Github gives you but it just has a different issuer. It has the same exact expiration and all that. As such I don't think it can be considered static, if you compare it to f.ex. having service account credentials.

> > All this aside, the ability to read the token from a file is something AWS already supports in their similar action. Why not have the possibility here too?
> 
> Because it's an [incorrect solution to the wrong problem](https://xyproblem.info). The point of OIDC is to exchange the machine/workload identity for another credential. Self-hosted GitHub Actions runners already have an identity provided by their underlying runtime.
> 
> Putting aside the fact that GitHub [requires exposing the `.well-known` endpoints as a mandatory prerequisite for OIDC](https://docs.github.com/en/enterprise-server@3.14/admin/managing-github-actions-for-your-enterprise/enabling-github-actions-for-github-enterprise-server/enabling-github-actions-with-google-cloud-storage#prerequisites)... if you _must_ trust the signatures from GHES, then the proper approach is to [sync the JWKS from on-prem into GCP with a small microservice or cron-job](https://cloud.google.com/iam/docs/workload-identity-federation-with-other-providers#manage-oidc-keys). It would periodically run something like:
> 
> ```shell
> curl -sfLO "https://github.company.internal/.well-known/jwks" && \
>   gcloud iam workload-identity-pools providers update-oidc "my-provider" --jwk-json-path="./jwks"
> ```
> 
> > ...there is no way to authenticate from Github enterprise towards google cloud in any other way than static credentials. This PR could bring mechanism to use "OIDC proxy" to get access working towards google cloud by using Github enterprise.
> 
> As I said above, that is simply untrue. Again, this approach is solving the _wrong problem_, and it's concerning that AWS would even allow this functionality in their action. You don't need an OIDC proxy, you need to sync the JWKS from GHES to GCP. The script I provided above is an example of how to do that. Or you could run a reverse proxy that _is_ exposed to the public Internet and only exposes the openid-connect and jwks endpoints.

I've understood that most of the companies running GHES tend to keep it unavailable publicly. The reverse proxy is not a real option either. The GHES instance may not necessarily even have it's DNS records public and the issuer of the token is not separately configurable in GHES as of today. As you also seem quite familiar with OIDC specification you're likely aware of the fact that the discovery endpoint (.well-known) needs to be the token issuer suffixed with /.well-known/openid-configuration.

At the end I guess the best option for us is to configure a cron job (or something similar) and sync the JWKS to a central project for managing pools and providers for workload identity federation. Thanks for your comments here.

**Pull request closed without merging**
